# -*- coding: utf-8 -*-
"""python_basics_<Narayana>.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13VXkxNDUCf8hn3rWXGkKUFAFlisTPYKt
"""

user_name= 'narayana'
print(user_name)

name= 'Narayana'
age= 30
height= 1.7
is_student= True
print(f"Name: {name} | Age: {age} | Height: {height} | Is_student: {is_student}")

age_months= age*12
age_days= age*365
age_remainder= age%7
age_power= age**2
print(f'Age_months: {age_months} |Age_days : {age_days} |Age_remainder: {age_remainder} |Age_power: {age_power}')

"""Task 1: Variables and Data Types Create variables to store a person's name (string), age (integer), height in meters (float), and whether they are a student (boolean). Print all four values in a single print() statement.

Task 2: String Formatting Using the variables from Task 1, print a sentence in the following format: Name: <name> | Age: <age> | Height: <height> | Student: <is_student>

Task 3: Arithmetic Operations Using the age variable, calculate and print:

Age in months
Age in days (assume 365 days/year)
The remainder when age is divided by 7
Age raised to the power of 2

"""